services:
  - type: web_service
    name: SpeakmateAI Backend
    env: java
    plan: free
    branch: main
    root: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
